version: "3"

services:
  jupyter:
    build:
      context: jupyter
      dockerfile: Dockerfile.cpu
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - NO_PROXY=${NO_PROXY}
        - http_proxy=${HTTP_PROXY}
        - https_proxy=${HTTPS_PROXY}
        - no_proxy=${NO_PROXY}
        - PYTHON_VERSION=3.9.5
    image: jupyterlab:cpu-latest
    environment:
        - JUPYTER_UID=${CONTAINER_UID}
        - PYTHON_VERSION=3.9.5
    volumes:
      - ./volume/jupyter:/opt/jupyter
      - ./volume/mlflow:/opt/mlflow
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "18080:8080"
    stop_signal: SIGINT

  mlflow:
    build:
      context: mlflow
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - NO_PROXY=${NO_PROXY}
        - http_proxy=${HTTP_PROXY}
        - https_proxy=${HTTPS_PROXY}
        - no_proxy=${NO_PROXY}
    image: mlflow
    environment:
      - MLRUNS_UID=${CONTAINER_UID}
    volumes:
      - ./volume/mlflow:/opt/mlflow
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "15000:5000"
    stop_signal: SIGINT
