version: "3"

services:
  jupyter:
    build:
      context: jupyter
      dockerfile: Dockerfile.gpu
      args:
        - DEVICE_TYPE=cu113
    image: tkscode/jupyterlab:gpu-1.3.0
    deploy:
      resources:
        reservations:
          devices:
            # GPU設定
            - driver: nvidia
              count: all
              capabilities: [gpu] # gpuを指定するとnvidia-smiとCUDAが利用できる
