version: "3"

services:
  jupyter:
    build:
      context: jupyter
      dockerfile: Dockerfile.gpu
      args:
        - IMAGE_CUDA_VERSION=${CUDA_VERSION:-11.8.0}
        - IMAGE_UBUNTU_VERSION=${UBUNTU_VERSION:-22.04}
    image: tkscode/jupyterlab:1.4.0-py${PYTHON_VERSION:-3.10.12}-cu${CUDA_VERSION:-11.8.0}
    deploy:
      resources:
        reservations:
          devices:
            # GPU設定
            - driver: nvidia
              count: all
              capabilities: [gpu] # gpuを指定するとnvidia-smiとCUDAが利用できる
