version: "3"

services:
  jupyter:
    build:
      context: jupyter
      dockerfile: Dockerfile.cpu
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - NO_PROXY=${NO_PROXY}
        - http_proxy=${HTTP_PROXY}
        - https_proxy=${HTTPS_PROXY}
        - no_proxy=${NO_PROXY}
        - PYTHON_VERSION=${PYTHON_VERSION:-3.10.12}
    image: tkscode/jupyterlab:1.4.0-cpu-py${PYTHON_VERSION:-3.10.12}
    environment:
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - NO_PROXY=${NO_PROXY}
      - JUPYTER_UID=${CONTAINER_UID}
      - JUPYTER_PASSWORD=${JUPYTER_PASSWORD}
      - PYTHON_VERSION=${PYTHON_VERSION:-3.10.12}
    volumes:
      - ./volume/jupyter:/opt/jupyter
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${JUPYTER_PORT:-8080}:8080"
    stop_signal: SIGINT
